amazon=read.table("C:/Users/bip/Desktop/thesis/data/amazon/5lakh.txt")
library(caret)
options("scipen"=100)
amazon$V2<-as.numeric(amazon$V2)
amazon$V3<-as.numeric(amazon$V3)
amazon1<-amazon[order(amazon$V2,amazon$V3),]
amazon1$V1=NULL
a=1
amazon1=cbind(amazon1,a)
amazon1$V1<-ave(amazon1$a,amazon$V3,FUN=sum)
amaz<-subset(amazon1,V1>=20)
amaz$V6<-ave(amaz$a,amaz$V2,FUN=sum)
amaz1<-subset(amaz,V6>=20)
mov_amaz=cbind(amaz1$V2,amaz1$V3,amaz1$V4,amaz1$V5)
amazon3<-as.data.frame(mov_amaz)

amazon3$V1<-as.factor(amazon3$V1)
amazon3$V2<-as.factor(amazon3$V2)
amazon3$V1<-as.numeric(amazon3$V1)
amazon3$V2<-as.numeric(amazon3$V2)
amazon4<-amazon3[order(amazon3$V1,amazon3$V2),]
library(caret)
max(train1$V2)
max(train1$V1)
max(amazon4$V2)
max(amazon4$V1)
flds <- createFolds(amazon4$V1, k = 5, list = TRUE, returnTrain = FALSE)
test1<-amazon4[flds[[1]],]
train1<-amazon4[-flds[[1]],]
test2<-amazon4[flds[[2]],]
train2<-amazon4[-flds[[2]],]
test3<-amazon4[flds[[3]],]
train3<-amazon4[-flds[[3]],]
test4<-amazon4[flds[[4]],]
train4<-amazon4[-flds[[4]],]
test5<-amazon4[flds[[5]],]
train5<-amazon4[-flds[[5]],]
write.table(test1,row.names=F,col.names=F,"C:/Users/bip/Desktop/thesis/data/amazon/test1.txt",sep="\t")
write.table(test2,row.names=F,col.names=F,"C:/Users/bip/Desktop/thesis/data/amazon/test2.txt",sep="\t")
write.table(test3,row.names=F,col.names=F,"C:/Users/bip/Desktop/thesis/data/amazon/test3.txt",sep="\t")
write.table(test4,row.names=F,col.names=F,"C:/Users/bip/Desktop/thesis/data/amazon/test4.txt",sep="\t")
write.table(test5,row.names=F,col.names=F,"C:/Users/bip/Desktop/thesis/data/amazon/test5.txt",sep="\t")
########################################
test1$V3=0
test2$V3=0
test3$V3=0
test4$V3=0
test5$V3=0
train1<-rbind(train1,test1)
train1<-train1[order(train1$V1,train1$V2),]
train2<-rbind(train2,test2)
train2<-train2[order(train2$V1,train2$V2),]
train3<-rbind(train3,test3)
train3<-train3[order(train3$V1,train3$V2),]
train4<-rbind(train4,test4)
train4<-train4[order(train4$V1,train4$V2),]
train5<-rbind(train5,test5)
train5<-train5[order(train5$V1,train5$V2),]
write.table(train1,row.names=F,col.names=F,"C:/Users/bip/Desktop/thesis/data/amazon/train1.txt",sep="\t")
write.table(train2,row.names=F,col.names=F,"C:/Users/bip/Desktop/thesis/data/amazon/train2.txt",sep="\t")
write.table(train3,row.names=F,col.names=F,"C:/Users/bip/Desktop/thesis/data/amazon/train3.txt",sep="\t")
write.table(train4,row.names=F,col.names=F,"C:/Users/bip/Desktop/thesis/data/amazon/train4.txt",sep="\t")
write.table(train5,row.names=F,col.names=F,"C:/Users/bip/Desktop/thesis/data/amazon/train5.txt",sep="\t")

#####################################################################################

options("scipen"=100)
mov_amaz=cbind(amaz1$V2,amaz1$V3,amaz1$V4,amaz1$V5)
amazon3<-as.data.frame(mov_amaz)
amazon3$V1<-as.factor(amazon3$V1)
amazon3$V2<-as.factor(amazon3$V2)
amazon3$V1<-as.numeric(amazon3$V1)
amazon3$V2<-as.numeric(amazon3$V2)
amazon4<-amazon3[order(amazon3$V1,amazon3$V1),]
amazon4<-amazon3[order(amazon3$V2,amazon3$V1),]

amazon$V1=NULL
amazon$V2<-as.numeric(amazon$V2)
amazon$V3<-as.numeric(amazon$V3)
amazon1<-amazon[order(amazon$V2),]
a=1
amazon1=cbind(amazon1,a)
amazon1$V1<-ave(amazon1$a,amazon1$V2,FUN=sum)

amaz<-subset(amazon1,V1>=5)
amaz$V6<-ave(amaz$a,amaz$V3,FUN=sum)
amaz1<-subset(amaz,V6>=5)
mov_amaz=cbind(amaz1$V2,amaz1$V3,amaz1$V4,amaz1$V5)
amazon3<-as.data.frame(mov_amaz)
amazon3$V1<-as.factor(amazon3$V1)
amazon3$V2<-as.factor(amazon3$V2)
amazon3$V1<-as.numeric(amazon3$V1)
amazon3$V2<-as.numeric(amazon3$V2)
amazon4<-amazon3[order(amazon3$V1,amazon3$V1),]
max(amazon4$V1)
min(amazon4$V1)
flds <- createFolds(amazon4$V1, k = 5, list = TRUE, returnTrain = FALSE)
#######################################################################
amazon$V6<-ifelse(amazon$V4>3,1,0)
library(dplyr)
amazon$V7<-ave(amazon$V6,amazon$V3,FUN=sum)
newdata <- amazon[order(-amazon$V7),] 
amazon1<-newdata[!duplicated(newdata[3]),]
library(ggplot2)
amazon1$V6=NULL
amazon2<-cbind(amazon1$V3,amazon1$V7)
amazon2<-data.frame(amazon2)
library(ggplot2)
ggplot(amazon1)
