nv=read.table("C:/Users/bip/Desktop/NV/Data_InCarMusic/Data_InCarMusic/Data_InCarMusic.txt",header=T,sep='\t')
nv1=as.matrix(nv)
nv1[is.na(nv1)] <- as.character("")
class(nv1)
nv1=as.data.frame(nv1)
nv1$land<-NULL
str(nv1)
nv1$landscape=as.character(nv1$landscape)
nv1$weather=as.character(nv1$weather)
nv1$final=nv1$landscape
nv=ifelse(nv1==0,"",as.factor(nv1))
write.table(nv1,row.names=FALSE,col.names=T, "E:/nv1.txt", sep="\t")
nv1=read.table("C:/Users/bip/Desktop/NV/nv1.txt",header=T,sep='\t')
nv1=cbind(nv1[,1:3],nv1$context)
nv1=rename(nv1,c('nv1$context'='samples'))
nv1$UserID=as.factor(nv1$UserID)
nv1$ItemID=as.factor(nv1$ItemID)
nv1$UserID=as.numeric(nv1$UserID)
nv1$ItemID=as.numeric(nv1$ItemID)
nv1$context=as.numeric(nv1$samples)

a=data.frame(nv[,4])
a=rename(a,c('nv...4.'='samples'))
b=data.frame(nv[,5])
b=rename(b,c('nv...5.'='samples'))
c=data.frame(nv[,6])
c=rename(c,c('nv...6.'='samples'))
d=data.frame(nv[,7])
d=rename(d,c('nv...7.'='samples'))
e=data.frame(nv[,8])
e=rename(e,c('nv...8.'='samples'))
f=data.frame(nv[,9])
f=rename(f,c('nv...9.'='samples'))
g=data.frame(nv[,10])
g=rename(g,c('nv...10.'='samples'))
h=data.frame(nv[,11])
h=rename(h,c('nv...11.'='samples'))
A=rbind(a,b,c,d,e,f,g,h)

B=subset(A,samples=NA)

library(plyr)
summary(a)
str(a)

a=as.factor(a)
